# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/wuyue/Project/fun/beyond_web/ui/home.ui',
# licensing of '/Users/wuyue/Project/fun/beyond_web/ui/home.ui' applies.
#
# Created: Thu Nov 21 15:52:55 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self._bookmark_dock = QtWidgets.QDockWidget(MainWindow)
        self._bookmark_dock.setObjectName("_bookmark_dock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self._bookmark_widget = BookmarkWidget(self.dockWidgetContents)
        self._bookmark_widget.setObjectName("_bookmark_widget")
        self.verticalLayout.addWidget(self._bookmark_widget)
        self._bookmark_dock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self._bookmark_dock)
        self._tool_bar = QtWidgets.QToolBar(MainWindow)
        self._tool_bar.setMovable(False)
        self._tool_bar.setObjectName("_tool_bar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self._tool_bar)
        self._menu = QtWidgets.QMenuBar()
        self._menu.setGeometry(QtCore.QRect(0, 0, 979, 22))
        self._menu.setObjectName("_menu")
        self.menuFile = QtWidgets.QMenu(self._menu)
        self.menuFile.setObjectName("menuFile")
        self.menuNavigation = QtWidgets.QMenu(self._menu)
        self.menuNavigation.setObjectName("menuNavigation")
        self.menuEdit = QtWidgets.QMenu(self._menu)
        self.menuEdit.setObjectName("menuEdit")
        self.menuBookmarks = QtWidgets.QMenu(self._menu)
        self.menuBookmarks.setObjectName("menuBookmarks")
        self.menuTools = QtWidgets.QMenu(self._menu)
        self.menuTools.setObjectName("menuTools")
        self.menuWindow = QtWidgets.QMenu(self._menu)
        self.menuWindow.setObjectName("menuWindow")
        self.menuAbout = QtWidgets.QMenu(self._menu)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self._menu)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.actionForward = QtWidgets.QAction(MainWindow)
        self.actionForward.setObjectName("actionForward")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionOpen_New_Window = QtWidgets.QAction(MainWindow)
        self.actionOpen_New_Window.setObjectName("actionOpen_New_Window")
        self.actionClose_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Tab.setObjectName("actionClose_Tab")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNew_Tab = QtWidgets.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionClose_Current_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Current_Tab.setObjectName("actionClose_Current_Tab")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionAdd_Bookmark = QtWidgets.QAction(MainWindow)
        self.actionAdd_Bookmark.setObjectName("actionAdd_Bookmark")
        self.actionAdd_Bookmark_to_Tool_Bar = QtWidgets.QAction(MainWindow)
        self.actionAdd_Bookmark_to_Tool_Bar.setObjectName("actionAdd_Bookmark_to_Tool_Bar")
        self.actionOpen_Downloads = QtWidgets.QAction(MainWindow)
        self.actionOpen_Downloads.setObjectName("actionOpen_Downloads")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionReset_Zoom = QtWidgets.QAction(MainWindow)
        self.actionReset_Zoom.setObjectName("actionReset_Zoom")
        self.actionAbout_byondWeb = QtWidgets.QAction(MainWindow)
        self.actionAbout_byondWeb.setObjectName("actionAbout_byondWeb")
        self._tool_bar.addAction(self.actionBack)
        self._tool_bar.addAction(self.actionForward)
        self._tool_bar.addAction(self.actionReload)
        self.menuFile.addAction(self.actionExit)
        self.menuNavigation.addAction(self.actionNew_Tab)
        self.menuNavigation.addAction(self.actionClose_Current_Tab)
        self.menuNavigation.addAction(self.actionHistory)
        self.menuEdit.addAction(self.actionFind)
        self.menuBookmarks.addAction(self.actionAdd_Bookmark)
        self.menuBookmarks.addAction(self.actionAdd_Bookmark_to_Tool_Bar)
        self.menuBookmarks.addSeparator()
        self.menuTools.addAction(self.actionOpen_Downloads)
        self.menuWindow.addAction(self.actionZoom_In)
        self.menuWindow.addAction(self.actionZoom_Out)
        self.menuWindow.addAction(self.actionReset_Zoom)
        self.menuAbout.addAction(self.actionAbout_byondWeb)
        self._menu.addAction(self.menuFile.menuAction())
        self._menu.addAction(self.menuNavigation.menuAction())
        self._menu.addAction(self.menuEdit.menuAction())
        self._menu.addAction(self.menuBookmarks.menuAction())
        self._menu.addAction(self.menuTools.menuAction())
        self._menu.addAction(self.menuWindow.menuAction())
        self._menu.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "beyondWeb", None, -1))
        self._bookmark_dock.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Bookmarks", None, -1))
        self._tool_bar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ToolBar", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuNavigation.setTitle(QtWidgets.QApplication.translate("MainWindow", "Navigation", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuBookmarks.setTitle(QtWidgets.QApplication.translate("MainWindow", "Bookmarks", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.menuWindow.setTitle(QtWidgets.QApplication.translate("MainWindow", "Window", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open New Tab", None, -1))
        self.actionEdit.setText(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionBack.setText(QtWidgets.QApplication.translate("MainWindow", "Back", None, -1))
        self.actionForward.setText(QtWidgets.QApplication.translate("MainWindow", "Forward", None, -1))
        self.actionReload.setText(QtWidgets.QApplication.translate("MainWindow", "Reload", None, -1))
        self.actionOpen_New_Window.setText(QtWidgets.QApplication.translate("MainWindow", "Open New Window", None, -1))
        self.actionClose_Tab.setText(QtWidgets.QApplication.translate("MainWindow", "Close Tab", None, -1))
        self.actionClose_Window.setText(QtWidgets.QApplication.translate("MainWindow", "Close Window", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionNew_Tab.setText(QtWidgets.QApplication.translate("MainWindow", "New Tab", None, -1))
        self.actionClose_Current_Tab.setText(QtWidgets.QApplication.translate("MainWindow", "Close Current Tab", None, -1))
        self.actionHistory.setText(QtWidgets.QApplication.translate("MainWindow", "History...", None, -1))
        self.actionFind.setText(QtWidgets.QApplication.translate("MainWindow", "Find", None, -1))
        self.actionAdd_Bookmark.setText(QtWidgets.QApplication.translate("MainWindow", "Add Bookmark", None, -1))
        self.actionAdd_Bookmark_to_Tool_Bar.setText(QtWidgets.QApplication.translate("MainWindow", "Add Bookmark to Tool Bar", None, -1))
        self.actionOpen_Downloads.setText(QtWidgets.QApplication.translate("MainWindow", "Open Downloads", None, -1))
        self.actionZoom_In.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In", None, -1))
        self.actionZoom_Out.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom Out", None, -1))
        self.actionReset_Zoom.setText(QtWidgets.QApplication.translate("MainWindow", "Reset Zoom", None, -1))
        self.actionAbout_byondWeb.setText(QtWidgets.QApplication.translate("MainWindow", "About byondWeb", None, -1))

from widgets.bookmarkwidget import BookmarkWidget
